language: python
sudo: false
matrix:
  include:
  - python: '3.6'
    env: DEPS="numpy scipy sympy"
install:
  - pip install --upgrade pip setuptools wheel
  - "pip install ${DEPS}"
  - pip install coveralls pytest pytest-cov
  - python install .
script:
- pytest -v --cov=cse --pyargs cse
